// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarBooks.Infrastructure.Books;

#nullable disable

namespace StarBooks.Infrastructure.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20220624141059_UseIntForPKs")]
    partial class UseIntForPKs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AuthorModelBookModel", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorModelBookModel");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.AuthorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("books");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BookModelId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookModelId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.IndustryIdentifierModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BookModelId")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookModelId");

                    b.ToTable("identifiers");
                });

            modelBuilder.Entity("AuthorModelBookModel", b =>
                {
                    b.HasOne("StarBooks.Domain.Books.AuthorModel", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarBooks.Domain.Books.BookModel", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarBooks.Domain.Books.BookModel", b =>
                {
                    b.OwnsOne("StarBooks.Domain.Books.AccessInfo", "AccessInfo", b1 =>
                        {
                            b1.Property<int>("BookModelId")
                                .HasColumnType("int");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Embeddable")
                                .HasColumnType("bit");

                            b1.Property<bool>("PublicDomain")
                                .HasColumnType("bit");

                            b1.Property<bool>("QuoteSharingAllowed")
                                .HasColumnType("bit");

                            b1.Property<string>("TextToSpeechPermission")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Viewability")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WebReaderLink")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BookModelId");

                            b1.ToTable("books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");

                            b1.OwnsOne("StarBooks.Domain.Books.EResource", "Epub", b2 =>
                                {
                                    b2.Property<int>("AccessInfoBookModelId")
                                        .HasColumnType("int");

                                    b2.Property<string>("AcsTokenLink")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool>("IsAvailable")
                                        .HasColumnType("bit");

                                    b2.HasKey("AccessInfoBookModelId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("AccessInfoBookModelId");
                                });

                            b1.OwnsOne("StarBooks.Domain.Books.EResource", "Pdf", b2 =>
                                {
                                    b2.Property<int>("AccessInfoBookModelId")
                                        .HasColumnType("int");

                                    b2.Property<string>("AcsTokenLink")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool>("IsAvailable")
                                        .HasColumnType("bit");

                                    b2.HasKey("AccessInfoBookModelId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("AccessInfoBookModelId");
                                });

                            b1.Navigation("Epub")
                                .IsRequired();

                            b1.Navigation("Pdf")
                                .IsRequired();
                        });

                    b.OwnsOne("StarBooks.Domain.Books.SaleInfo", "SaleInfo", b1 =>
                        {
                            b1.Property<int>("BookModelId")
                                .HasColumnType("int");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsEbook")
                                .HasColumnType("bit");

                            b1.HasKey("BookModelId");

                            b1.ToTable("books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");

                            b1.OwnsOne("StarBooks.Domain.Books.Price", "ListPrice", b2 =>
                                {
                                    b2.Property<int>("SaleInfoBookModelId")
                                        .HasColumnType("int");

                                    b2.HasKey("SaleInfoBookModelId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleInfoBookModelId");
                                });

                            b1.OwnsOne("StarBooks.Domain.Books.Price", "RetailPrice", b2 =>
                                {
                                    b2.Property<int>("SaleInfoBookModelId")
                                        .HasColumnType("int");

                                    b2.HasKey("SaleInfoBookModelId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleInfoBookModelId");
                                });

                            b1.Navigation("ListPrice")
                                .IsRequired();

                            b1.Navigation("RetailPrice")
                                .IsRequired();
                        });

                    b.OwnsOne("StarBooks.Domain.Books.SearchInfo", "SearchInfo", b1 =>
                        {
                            b1.Property<int>("BookModelId")
                                .HasColumnType("int");

                            b1.HasKey("BookModelId");

                            b1.ToTable("books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");
                        });

                    b.OwnsOne("StarBooks.Domain.Books.VolumeInfo", "VolumeInfo", b1 =>
                        {
                            b1.Property<int>("BookModelId")
                                .HasColumnType("int");

                            b1.Property<double>("AverageRating")
                                .HasColumnType("float");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("InfoLink")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("PageCount")
                                .HasColumnType("int");

                            b1.Property<string>("PreviewLink")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PrintType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PublishedDate")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Publisher")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("RatingsCount")
                                .HasColumnType("int");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BookModelId");

                            b1.ToTable("books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");

                            b1.OwnsOne("StarBooks.Domain.Books.ImageLinks", "ImageLinks", b2 =>
                                {
                                    b2.Property<int>("VolumeInfoBookModelId")
                                        .HasColumnType("int");

                                    b2.Property<string>("ThumbnailUrl")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("VolumeInfoBookModelId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("VolumeInfoBookModelId");
                                });

                            b1.Navigation("ImageLinks")
                                .IsRequired();
                        });

                    b.Navigation("AccessInfo")
                        .IsRequired();

                    b.Navigation("SaleInfo")
                        .IsRequired();

                    b.Navigation("SearchInfo")
                        .IsRequired();

                    b.Navigation("VolumeInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("StarBooks.Domain.Books.CategoryModel", b =>
                {
                    b.HasOne("StarBooks.Domain.Books.BookModel", null)
                        .WithMany("Categories")
                        .HasForeignKey("BookModelId");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.IndustryIdentifierModel", b =>
                {
                    b.HasOne("StarBooks.Domain.Books.BookModel", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("BookModelId");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.BookModel", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Identifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
