// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarBooks.Infrastructure.Books;

#nullable disable

namespace StarBooks.Infrastructure.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20220628085437_EnableMoreNullableFields")]
    partial class EnableMoreNullableFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AuthorModelBookModel", b =>
                {
                    b.Property<int>("AuthorsAuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BooksBookId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsAuthorId", "BooksBookId");

                    b.HasIndex("BooksBookId");

                    b.ToTable("AuthorModelBookModel");
                });

            modelBuilder.Entity("BookModelCategoryModel", b =>
                {
                    b.Property<int>("BooksBookId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesCategoryId")
                        .HasColumnType("int");

                    b.HasKey("BooksBookId", "CategoriesCategoryId");

                    b.HasIndex("CategoriesCategoryId");

                    b.ToTable("BookModelCategoryModel");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.AuthorModel", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.BookModel", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.HasKey("BookId");

                    b.ToTable("books");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.IndustryIdentifierModel", b =>
                {
                    b.Property<int>("IdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentifierId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentifierId");

                    b.HasIndex("BookId");

                    b.ToTable("identifiers");
                });

            modelBuilder.Entity("AuthorModelBookModel", b =>
                {
                    b.HasOne("StarBooks.Domain.Books.AuthorModel", null)
                        .WithMany()
                        .HasForeignKey("AuthorsAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarBooks.Domain.Books.BookModel", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookModelCategoryModel", b =>
                {
                    b.HasOne("StarBooks.Domain.Books.BookModel", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarBooks.Domain.Books.CategoryModel", null)
                        .WithMany()
                        .HasForeignKey("CategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarBooks.Domain.Books.BookModel", b =>
                {
                    b.OwnsOne("StarBooks.Domain.Books.AccessInfo", "AccessInfo", b1 =>
                        {
                            b1.Property<int>("BookModelBookId")
                                .HasColumnType("int");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("Embeddable")
                                .HasColumnType("bit");

                            b1.Property<bool?>("PublicDomain")
                                .HasColumnType("bit");

                            b1.Property<bool?>("QuoteSharingAllowed")
                                .HasColumnType("bit");

                            b1.Property<string>("TextToSpeechPermission")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Viewability")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WebReaderLink")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BookModelBookId");

                            b1.ToTable("books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelBookId");

                            b1.OwnsOne("StarBooks.Domain.Books.EResource", "Epub", b2 =>
                                {
                                    b2.Property<int>("AccessInfoBookModelBookId")
                                        .HasColumnType("int");

                                    b2.Property<string>("AcsTokenLink")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsAvailable")
                                        .HasColumnType("bit");

                                    b2.HasKey("AccessInfoBookModelBookId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("AccessInfoBookModelBookId");
                                });

                            b1.OwnsOne("StarBooks.Domain.Books.EResource", "Pdf", b2 =>
                                {
                                    b2.Property<int>("AccessInfoBookModelBookId")
                                        .HasColumnType("int");

                                    b2.Property<string>("AcsTokenLink")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool?>("IsAvailable")
                                        .HasColumnType("bit");

                                    b2.HasKey("AccessInfoBookModelBookId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("AccessInfoBookModelBookId");
                                });

                            b1.Navigation("Epub")
                                .IsRequired();

                            b1.Navigation("Pdf")
                                .IsRequired();
                        });

                    b.OwnsOne("StarBooks.Domain.Books.SaleInfo", "SaleInfo", b1 =>
                        {
                            b1.Property<int>("BookModelBookId")
                                .HasColumnType("int");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsEbook")
                                .HasColumnType("bit");

                            b1.HasKey("BookModelBookId");

                            b1.ToTable("books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelBookId");

                            b1.OwnsOne("StarBooks.Domain.Books.Price", "ListPrice", b2 =>
                                {
                                    b2.Property<int>("SaleInfoBookModelBookId")
                                        .HasColumnType("int");

                                    b2.Property<decimal?>("Amount")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("CurrencyCode")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SaleInfoBookModelBookId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleInfoBookModelBookId");
                                });

                            b1.OwnsOne("StarBooks.Domain.Books.Price", "RetailPrice", b2 =>
                                {
                                    b2.Property<int>("SaleInfoBookModelBookId")
                                        .HasColumnType("int");

                                    b2.Property<decimal?>("Amount")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("CurrencyCode")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SaleInfoBookModelBookId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleInfoBookModelBookId");
                                });

                            b1.Navigation("ListPrice")
                                .IsRequired();

                            b1.Navigation("RetailPrice")
                                .IsRequired();
                        });

                    b.OwnsOne("StarBooks.Domain.Books.SearchInfo", "SearchInfo", b1 =>
                        {
                            b1.Property<int>("BookModelBookId")
                                .HasColumnType("int");

                            b1.Property<string>("TextSnippet")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BookModelBookId");

                            b1.ToTable("books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelBookId");
                        });

                    b.OwnsOne("StarBooks.Domain.Books.VolumeInfo", "VolumeInfo", b1 =>
                        {
                            b1.Property<int>("BookModelBookId")
                                .HasColumnType("int");

                            b1.Property<double?>("AverageRating")
                                .HasColumnType("float");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("InfoLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Language")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("PageCount")
                                .HasColumnType("int");

                            b1.Property<string>("PreviewLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PrintType")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("PublishedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Publisher")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("RatingsCount")
                                .HasColumnType("int");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BookModelBookId");

                            b1.ToTable("books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelBookId");

                            b1.OwnsOne("StarBooks.Domain.Books.ImageLinks", "ImageLinks", b2 =>
                                {
                                    b2.Property<int>("VolumeInfoBookModelBookId")
                                        .HasColumnType("int");

                                    b2.Property<string>("ThumbnailUrl")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("VolumeInfoBookModelBookId");

                                    b2.ToTable("books");

                                    b2.WithOwner()
                                        .HasForeignKey("VolumeInfoBookModelBookId");
                                });

                            b1.Navigation("ImageLinks")
                                .IsRequired();
                        });

                    b.Navigation("AccessInfo")
                        .IsRequired();

                    b.Navigation("SaleInfo")
                        .IsRequired();

                    b.Navigation("SearchInfo")
                        .IsRequired();

                    b.Navigation("VolumeInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("StarBooks.Domain.Books.IndustryIdentifierModel", b =>
                {
                    b.HasOne("StarBooks.Domain.Books.BookModel", "Book")
                        .WithMany("Identifiers")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("StarBooks.Domain.Books.BookModel", b =>
                {
                    b.Navigation("Identifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
