version: '3.8'

services:
  catalog-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-microservice
    env_file:
      - .env
    ports:
      - "50051:${GRPC_PORT}"
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:${MONGO_PORT}"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - ./data:/data/db

  mongodb-seed:
    image: mongo:latest
    container_name: mongodb-seed
    depends_on:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    links:
      - mongodb
    command:
      mongoimport --host mongodb --db $MONGO_DB --collection $MONGO_COLLECTION --type json --file /mongo-seed/book-init.json --jsonArray --authenticationDatabase admin --username $MONGO_USER --password $MONGO_PASS